server {
    listen 8080;
    root ./www1;
    index index1.html;

    location / {
        root ./www1;
        index home.html;
    }
}

server {
    listen 9090;
    root ./www2;
    index index2.html;

    location /images {
        root ./images;
        index gallery.html;
    }
}