server {
    listen 8080;
    root ./www;
    index index.html;

    location / {
        root ./www;
        index index.html;
    }
}

server {
    listen 9090;
    root ./www2;
    index index2.html;
    location /images {
        root ./images;
        index gallery.html;
    }
}