server {
    listen 8080 8888 9999;
    root ./www;
    index index.html;

    location / {
        root ./www;
        index index.html;
    }
    location /upload {
    upload_path ./uploads;
    }
}

server {
    listen 9090;
    root ./www2;
    index index2.html;
    location /images {
        root ./images;
        index gallery.html;
    }
}