server {
    listen 8080;
    root ./www;
    index index.html;

    location / {
        root ./www;
        index index.html;
    }
        location /cgi-bin {
        root ./config_cgi;
        cgi .py /usr/bin/python3;
    }


    location /upload {
        root ./uploads;
    }
}